services:
  - type: web
    name: veda-assessment-backend
    runtime: node
    plan: free
    branch: main
    buildCommand: cd backend && npm ci && npm run build
    startCommand: cd backend && npm run start

  - type: web
    name: veda-assessment-frontend
    runtime: node
    plan: free
    branch: main
    buildCommand: cd frontend && npm ci && npm run build
    startCommand: cd frontend && npm run start -- -p $PORT
    envVars:
      - key: NEXT_PUBLIC_API_BASE
        value: "https://veda-assessment-backend.onrender.com/api"
      - key: NEXT_PUBLIC_WS_BASE
        value: "https://veda-assessment-backend.onrender.com"
